version: "2.4"

services:
  iroha_node_0:
    image: soramitsu/iroha:1.4.0-patch-2
    container_name: iroha_node_0
    ports:
      - 50051:50051
    environment:
      - "KEY=node0"
      - "IROHA_POSTGRES_HOST=postgres_0"
    volumes:
      - ./node0/config:/opt/iroha_data
      - ./node0/block_store:/tmp/block_store
    depends_on:
      - postgres_0
    networks:
      - iroha-network
    restart: always
  
  postgres_0:
    image: postgres:9.5
    container_name: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    networks:
      - iroha-network
    restart: always

  iroha_node_1:
    image: soramitsu/iroha:1.4.0-patch-2
    container_name: iroha_node_1
    ports:
      - 50052:50051
    environment:
      - "KEY=node1"
      - "IROHA_POSTGRES_HOST=postgres_1"
    volumes:
      - ./node1/config:/opt/iroha_data
      - ./node1/block_store:/tmp/block_store
    depends_on:
      - postgres_1
    networks:
      - iroha-network
    restart: always
  
  postgres_1:
    image: postgres:9.5
    container_name: postgres_1
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5433
    networks:
      - iroha-network
    restart: always

  iroha_node_2:
    image: soramitsu/iroha:1.4.0-patch-2
    container_name: iroha_node_2
    ports:
      - 50053:50051
    environment:
      - "KEY=node2"
      - "IROHA_POSTGRES_HOST=postgres_2"
    volumes:
      - ./node2/config:/opt/iroha_data
      - ./node2/block_store:/tmp/block_store
    depends_on:
      - postgres_2
    networks:
      - iroha-network
    restart: always
  
  postgres_2:
    image: postgres:9.5
    container_name: postgres_2
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5434
    networks:
      - iroha-network
    restart: always

  iroha_node_3:
    image: soramitsu/iroha:1.4.0-patch-2
    container_name: iroha_node_3
    ports:
      - 50054:50051
    environment:
      - "KEY=node3"
      - "IROHA_POSTGRES_HOST=postgres_3"
    volumes:
      - ./node3/config:/opt/iroha_data
      - ./node3/block_store:/tmp/block_store
    depends_on:
      - postgres_3
    networks:
      - iroha-network
    restart: always
  
  postgres_3:
    image: postgres:9.5
    container_name: postgres_3
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5435
    networks:
      - iroha-network
    restart: always

  iroha_node_4:
    image: soramitsu/iroha:1.4.0-patch-2
    container_name: iroha_node_4
    expose:
      - 10001
    environment:
      - "KEY=node4"
      - "IROHA_POSTGRES_HOST=postgres_4"
    volumes:
      - ./node4/config:/opt/iroha_data
      - ./node4/block_store:/tmp/block_store
    command:
      - "--syncing_node"
    depends_on:
      - postgres_4
    networks:
      - iroha-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    mem_limit: "1024m"
    restart: always
  
  postgres_4:
    image: postgres:9.5
    container_name: postgres_4
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5436
    networks:
      - iroha-network
    restart: always
  
networks:
  iroha-network:
    name: iroha-network